#ifndef PROTOCOL_VERSION_H
#define PROTOCOL_VERSION_H

#define HERMES_PROTOCOL_MAJOR    (1U)
#define HERMES_PROTOCOL_MINOR    (0U)
#define HERMES_PROTOCOL_PATCH    (0U)

#define HERMES_PROTOCOL_VERSION  (0x010000U)

#endif